# Generated by Django 3.2.7 on 2022-12-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productCRUD', '0003_auto_20221204_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='productCRUD.product_category'),
        ),
    ]
