# Generated by Django 4.1 on 2022-12-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productCRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Checkout',
                'ordering': '',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('checkout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
                ('product_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productCRUD.product')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_quantity',
            field=models.ManyToManyField(through='checkout.ProductQuantity', to='productCRUD.product'),
        ),
    ]
