# Generated by Django 3.2.7 on 2022-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCRUD', '0001_initial'),
        ('checkout', '0002_alter_checkout_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='checkout',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='products_quantity',
            field=models.ManyToManyField(through='checkout.ProductQuantity', to='productCRUD.Product'),
        ),
    ]
