# Generated by Django 3.2.7 on 2022-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20221204_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquantity',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
